plugins:
    deadline_enabled:
        default: true
        client: true
    deadline_allowed_on_categories:
        default: ''
        type: category_list
        client: true
    deadline_auto_bump_topic:
        default: false
    deadline_auto_bump_topic_threshold:
        default: 2
    deadline_soon_days_threshold:
        default: 2
        client: true
        min: 0
        max: 30
